name = "tmail-backend"
main = "src/index.ts"

# 打包配置
minify = true # 生产环境压缩代码
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-03-01"

# 配置环境变量
# 注意: API_TOKEN应通过Cloudflare Dashboard或CLI设置
# wrangler secret put API_TOKEN
[vars]
# 这里可以设置默认值，但建议通过Cloudflare Dashboard或CLI设置
# API_TOKEN = "your-default-token" # 建议在生产环境中通过Cloudflare Dashboard配置

# 启用 D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "temp_mail"
database_id = ""  # 需要替换为您的实际数据库 ID

# 配置邮件处理
[triggers]
crons = ["0 * * * *"]  # 每小时运行一次清理任务

[build]
command = "" # 使用默认打包，不需要自定义构建命令

# 默认开启日志，方便调试
[observability]
enabled = enabled
head_sampling_rate = 1 # optional. default = 1.
